// `category` is a category slug; seed.js swaps it for the category id.
// Images are expected at frontend/public/images/menu/<slug>.webp (added in Phase 3).

const menuData = [
  // Coffee
  {
    name: 'Espresso',
    category: 'coffee',
    price: 3.0,
    description: 'A short, syrupy double shot of our house blend with notes of dark cocoa.',
    ingredients: ['Double espresso'],
    tags: ['veg', 'strong'],
    calories: 5,
  },
  {
    name: 'Flat White',
    category: 'coffee',
    price: 4.5,
    description: 'Double ristretto with silky steamed milk. Strong, smooth, and not sweet.',
    ingredients: ['Double ristretto', 'Whole milk'],
    tags: ['veg', 'popular', 'strong'],
    calories: 120,
  },
  {
    name: 'Cardamom Latte',
    category: 'coffee',
    price: 5.2,
    description: 'Espresso and steamed milk with house-made green cardamom syrup.',
    ingredients: ['Espresso', 'Whole milk', 'Cardamom syrup'],
    tags: ['veg', 'popular', 'sweet'],
    calories: 190,
  },
  {
    name: 'Oat Cortado',
    category: 'coffee',
    price: 4.6,
    description: 'Equal parts espresso and creamy oat milk. Plant-based and balanced.',
    ingredients: ['Espresso', 'Oat milk'],
    tags: ['veg', 'strong'],
    calories: 90,
  },
  {
    name: 'Honey Cinnamon Cappuccino',
    category: 'coffee',
    price: 5.0,
    description: 'Classic cappuccino with wildflower honey and a dusting of cinnamon.',
    ingredients: ['Espresso', 'Whole milk', 'Honey', 'Cinnamon'],
    tags: ['veg', 'sweet'],
    calories: 170,
  },
  {
    name: 'Single Origin Pour Over',
    category: 'coffee',
    price: 5.5,
    description: 'Hand-brewed Ethiopian Yirgacheffe with bright citrus and jasmine notes.',
    ingredients: ['Single origin coffee', 'Filtered water'],
    tags: ['veg', 'new'],
    calories: 5,
  },

  // Cold Drinks
  {
    name: 'Iced Spanish Latte',
    category: 'cold-drinks',
    price: 5.6,
    description: 'Espresso over ice with cold milk and a ribbon of condensed milk.',
    ingredients: ['Espresso', 'Milk', 'Condensed milk', 'Ice'],
    tags: ['veg', 'popular', 'sweet', 'iced'],
    calories: 240,
  },
  {
    name: 'Cold Brew',
    category: 'cold-drinks',
    price: 4.8,
    description: 'Steeped for 18 hours for a smooth, low-acid, high-caffeine cup.',
    ingredients: ['Cold brew coffee', 'Ice'],
    tags: ['veg', 'strong', 'iced'],
    calories: 10,
  },
  {
    name: 'Espresso Tonic',
    category: 'cold-drinks',
    price: 5.2,
    description: 'A double shot poured over tonic water and orange peel. Bitter and bright.',
    ingredients: ['Espresso', 'Tonic water', 'Orange peel', 'Ice'],
    tags: ['veg', 'strong', 'iced', 'new'],
    calories: 70,
  },
  {
    name: 'Iced Matcha Latte',
    category: 'cold-drinks',
    price: 5.4,
    description: 'Ceremonial-grade matcha whisked and poured over cold oat milk.',
    ingredients: ['Matcha', 'Oat milk', 'Ice'],
    tags: ['veg', 'iced'],
    calories: 150,
  },
  {
    name: 'Mango Passion Cooler',
    category: 'cold-drinks',
    price: 4.9,
    description: 'Alphonso mango and passion fruit shaken with mint and soda. No caffeine.',
    ingredients: ['Mango', 'Passion fruit', 'Mint', 'Soda water', 'Ice'],
    tags: ['veg', 'sweet', 'iced'],
    calories: 160,
  },
  {
    name: 'Hibiscus Lemonade',
    category: 'cold-drinks',
    price: 4.2,
    description: 'Tart hibiscus tea with fresh lemon and a light touch of cane sugar.',
    ingredients: ['Hibiscus tea', 'Lemon', 'Cane sugar', 'Ice'],
    tags: ['veg', 'iced'],
    calories: 110,
  },

  // Bakery
  {
    name: 'Butter Croissant',
    category: 'bakery',
    price: 3.4,
    description: 'Laminated over three days for a crisp shell and a soft, honeycomb crumb.',
    ingredients: ['Flour', 'French butter', 'Milk', 'Yeast'],
    tags: ['veg', 'popular'],
    calories: 280,
  },
  {
    name: 'Almond Croissant',
    category: 'bakery',
    price: 4.2,
    description: 'Twice-baked croissant filled with almond frangipane and toasted flakes.',
    ingredients: ['Croissant', 'Almond cream', 'Flaked almonds', 'Icing sugar'],
    tags: ['veg', 'sweet'],
    calories: 420,
  },
  {
    name: 'Cardamom Bun',
    category: 'bakery',
    price: 3.9,
    description: 'Scandinavian knot bun with cardamom sugar and a pearl sugar crust.',
    ingredients: ['Flour', 'Butter', 'Cardamom', 'Pearl sugar'],
    tags: ['veg', 'popular', 'sweet'],
    calories: 330,
  },
  {
    name: 'Blueberry Muffin',
    category: 'bakery',
    price: 3.6,
    description: 'Buttermilk muffin packed with blueberries under a crunchy crumble top.',
    ingredients: ['Flour', 'Blueberries', 'Buttermilk', 'Brown sugar crumble'],
    tags: ['veg', 'sweet'],
    calories: 390,
  },
  {
    name: 'Sourdough Toast and Butter',
    category: 'bakery',
    price: 4.5,
    description: 'Two thick slices of 36-hour sourdough with cultured butter and sea salt.',
    ingredients: ['Sourdough', 'Cultured butter', 'Sea salt'],
    tags: ['veg'],
    calories: 310,
  },
  {
    name: 'Pistachio Danish',
    category: 'bakery',
    price: 4.4,
    description: 'Flaky pastry with pistachio cream and a sour cherry center.',
    ingredients: ['Puff pastry', 'Pistachio cream', 'Sour cherries'],
    tags: ['veg', 'sweet', 'new'],
    calories: 380,
  },

  // Snacks
  {
    name: 'Avocado Toast',
    category: 'snacks',
    price: 7.2,
    description: 'Smashed avocado on sourdough with chili flakes, lime, and seeds.',
    ingredients: ['Sourdough', 'Avocado', 'Chili flakes', 'Lime', 'Pumpkin seeds'],
    tags: ['veg', 'popular'],
    calories: 410,
  },
  {
    name: 'Cheese Toastie',
    category: 'snacks',
    price: 6.2,
    description: 'Aged cheddar and mozzarella pressed in buttered sourdough until golden.',
    ingredients: ['Sourdough', 'Cheddar', 'Mozzarella', 'Butter'],
    tags: ['veg'],
    calories: 520,
  },
  {
    name: 'Hummus and Warm Pita',
    category: 'snacks',
    price: 6.5,
    description: 'Silky hummus with olive oil, paprika, and warm pita for sharing.',
    ingredients: ['Chickpeas', 'Tahini', 'Olive oil', 'Pita bread'],
    tags: ['veg'],
    calories: 450,
  },
  {
    name: 'Loaded Masala Fries',
    category: 'snacks',
    price: 5.8,
    description: 'Crispy fries tossed in house masala with garlic mayo and green chutney.',
    ingredients: ['Potatoes', 'Masala spice', 'Garlic mayo', 'Mint chutney'],
    tags: ['veg', 'popular'],
    calories: 560,
  },
  {
    name: 'Spiced Chickpea Chaat',
    category: 'snacks',
    price: 5.4,
    description: 'Tangy chickpeas with yogurt, tamarind, onion, and crunchy sev.',
    ingredients: ['Chickpeas', 'Yogurt', 'Tamarind chutney', 'Onion', 'Sev'],
    tags: ['veg', 'new'],
    calories: 340,
  },
  {
    name: 'Chicken Spring Rolls',
    category: 'snacks',
    price: 6.0,
    description: 'Four crisp rolls with spiced chicken and vegetables, sweet chili dip.',
    ingredients: ['Chicken', 'Cabbage', 'Carrot', 'Spring roll pastry', 'Sweet chili sauce'],
    tags: [],
    calories: 380,
  },

  // Meals
  {
    name: 'Chicken Tikka Rice Bowl',
    category: 'meals',
    price: 11.5,
    description: 'Charred tikka chicken over saffron rice with pickled onions and raita.',
    ingredients: ['Chicken tikka', 'Saffron rice', 'Pickled onion', 'Cucumber raita'],
    tags: ['popular'],
    calories: 690,
  },
  {
    name: 'Grilled Chicken Pesto Sandwich',
    category: 'meals',
    price: 9.5,
    description: 'Grilled chicken, basil pesto, sun-dried tomato, and rocket on ciabatta.',
    ingredients: ['Ciabatta', 'Grilled chicken', 'Basil pesto', 'Sun-dried tomato', 'Rocket'],
    tags: [],
    calories: 620,
  },
  {
    name: 'Creamy Mushroom Pasta',
    category: 'meals',
    price: 10.8,
    description: 'Rigatoni in a garlic and parmesan cream sauce with roasted mushrooms.',
    ingredients: ['Rigatoni', 'Mushrooms', 'Cream', 'Parmesan', 'Garlic'],
    tags: ['veg'],
    calories: 740,
  },
  {
    name: 'Halloumi Grain Bowl',
    category: 'meals',
    price: 10.5,
    description: 'Grilled halloumi, quinoa, roasted vegetables, hummus, and lemon dressing.',
    ingredients: ['Halloumi', 'Quinoa', 'Roasted vegetables', 'Hummus', 'Lemon dressing'],
    tags: ['veg', 'new'],
    calories: 610,
  },
  {
    name: 'Alladin Smash Burger',
    category: 'meals',
    price: 12.0,
    description: 'Two smashed beef patties, cheddar, pickles, and house sauce on brioche.',
    ingredients: ['Beef patties', 'Cheddar', 'Pickles', 'House sauce', 'Brioche bun'],
    tags: ['popular'],
    calories: 880,
  },
  {
    name: 'Big Breakfast Plate',
    category: 'meals',
    price: 12.5,
    description: 'Eggs your way, chicken sausage, beans, mushrooms, and sourdough. All day.',
    ingredients: ['Eggs', 'Chicken sausage', 'Baked beans', 'Mushrooms', 'Sourdough'],
    tags: [],
    calories: 920,
  },

  // Desserts
  {
    name: 'Basque Cheesecake',
    category: 'desserts',
    price: 5.8,
    description: 'Burnt-top cheesecake with a creamy, just-set center.',
    ingredients: ['Cream cheese', 'Eggs', 'Cream', 'Sugar'],
    tags: ['veg', 'popular', 'sweet'],
    calories: 460,
  },
  {
    name: 'Molten Chocolate Cake',
    category: 'desserts',
    price: 6.2,
    description: 'Warm dark chocolate cake with a flowing center and vanilla ice cream.',
    ingredients: ['Dark chocolate', 'Butter', 'Eggs', 'Vanilla ice cream'],
    tags: ['veg', 'sweet'],
    calories: 540,
  },
  {
    name: 'Classic Tiramisu',
    category: 'desserts',
    price: 6.0,
    description: 'Espresso-soaked ladyfingers layered with mascarpone and cocoa.',
    ingredients: ['Ladyfingers', 'Espresso', 'Mascarpone', 'Cocoa'],
    tags: ['veg', 'sweet'],
    calories: 450,
  },
  {
    name: 'Pistachio Kunafa',
    category: 'desserts',
    price: 6.5,
    description: 'Crisp kataifi pastry with sweet cheese, pistachio, and rose syrup.',
    ingredients: ['Kataifi pastry', 'Sweet cheese', 'Pistachio', 'Rose syrup'],
    tags: ['veg', 'sweet', 'new'],
    calories: 520,
  },
  {
    name: 'Lotus Cheesecake Jar',
    category: 'desserts',
    price: 5.5,
    description: 'No-bake Biscoff cheesecake layered in a jar with caramelized crumbs.',
    ingredients: ['Cream cheese', 'Biscoff spread', 'Biscoff crumbs', 'Cream'],
    tags: ['veg', 'sweet'],
    calories: 490,
  },
  {
    name: 'Salted Caramel Brownie',
    category: 'desserts',
    price: 4.2,
    description: 'Fudgy dark chocolate brownie swirled with salted caramel.',
    ingredients: ['Dark chocolate', 'Butter', 'Brown sugar', 'Salted caramel'],
    tags: ['veg', 'sweet', 'popular'],
    calories: 430,
  },
];

export default menuData;
