// `daysFromNow` is converted to a YYYY-MM-DD date when seeding.
const reservationData = [
  {
    name: 'Ayesha Malik',
    email: 'customer@alladin.cafe',
    phone: '+00 987 654 321',
    daysFromNow: 1,
    time: '10:00',
    guests: 1,
    seatType: 'study-desk',
    status: 'approved',
    notes: 'Quiet room if possible.',
    linkCustomer: true,
  },
  {
    name: 'Hamza Qureshi',
    email: 'hamza@example.com',
    phone: '+00 555 010 200',
    daysFromNow: 1,
    time: '19:30',
    guests: 4,
    seatType: 'table',
    status: 'pending',
    notes: 'Birthday dinner.',
  },
  {
    name: 'Laiba Ahmed',
    email: 'laiba@example.com',
    phone: '+00 555 010 300',
    daysFromNow: 2,
    time: '14:00',
    guests: 1,
    seatType: 'study-desk',
    status: 'pending',
  },
  {
    name: 'Omar Siddiqui',
    email: 'omar@example.com',
    phone: '+00 555 010 400',
    daysFromNow: 3,
    time: '12:30',
    guests: 2,
    seatType: 'table',
    status: 'approved',
  },
  {
    name: 'Ayesha Malik',
    email: 'customer@alladin.cafe',
    phone: '+00 987 654 321',
    daysFromNow: -2,
    time: '16:00',
    guests: 3,
    seatType: 'table',
    status: 'rejected',
    notes: 'Fully booked at that time.',
    linkCustomer: true,
  },
];

export default reservationData;
